---
- name: optional packages but might be useful
  become: yes
  become_method: sudo
  apt: pkg="{{ item }}" state=latest
  with_items:
  - nikto
  - w3af
  - wapiti
  - nmap
  - ratproxy
  - skipfish
  - spikeproxy
  - hydra
  - hydra-gtk
  - jxplorer
  - wireshark
  - hping3
  - mz
  - mitmproxy
  - sslstrip
  - ettercap-graphical
  - ettercap-common
  - sslscan
  - stunnel
  - socat
  - zaproxy
  - burpsuite-free
  - tcpdump
  - tshark
