---
# - name: get ip address
#   command: ifconfig
#     become: yes
#    become_method: sudo

- name: read hosts file
  command: cat /etc/hosts

- name: install packages
  apt: pkg=htop state=latest
  become: yes
  become_method: sudo