---
- name: install packages essential for ansible+vagrant stuff
  become: yes
  become_method: sudo
  apt: pkg="{{ item }}" state=latest
  with_items:
  - python-apt
  - python-pycurl

- name: update the system
  become: yes
  become_method: sudo
  apt: update_cache=yes
  
- name: upgrade the system
  become: yes
  become_method: sudo 
  apt: upgrade=full
